/** Structured content generated by the AI pipeline for a single video. */
export interface Scene {
  index: number;
  heading: string;
  narration: string;
  caption: string;
  durationSec: number;
  /** 0-100 accent used for on-screen stat/highlight, optional. */
  stat?: string;
}

export interface GeneratedContent {
  topic: string;
  title: string;
  hook: string;
  script: string;
  scenes: Scene[];
  caption: string;
  hashtags: string[];
  tiktokDescription: string;
  instagramDescription: string;
  youtubeDescription: string;
  thumbnailText: string;
  cta: string;
}

export interface GenerateRequest {
  templateKey: string;
  topic?: string;
  tone?: string;
  audience?: string;
}
